[build]
  dockerfile = "./Dockerfile"

[env]
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
